Sublocations2
Octember/the-approach pull request #17
Opened 2018-01-15 00:53 UTC by ezraschwaa

## Description
Added text to sublocation cards.  
Also adjusted spacing and added shadow. 
![image](https://user-images.githubusercontent.com/15095373/34922956-691b7992-f964-11e7-88a3-eb2e8538d0fa.png)

2018-01-16 00:42 UTC, Octember commented on app/components/shared/PageTitle/index.js
> +  font-family: AvenirNext-Bold;
This wont work -- we don't have Avenir yet, for cow change it back to Raleway. We'll do font stuff later

2018-01-16 00:46 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +                  <img src="https://www.shareicon.net/data/128x128/2016/06/06/582476_location_16x16.png" width = "12" height = "15.6"/>
For these static assets, we should save the images into the repo and load them from our own servers. Do you know if we are allowed to use them? Don't worry about this yet for this PR, we haven't done it yet in this project so I'll figure that out soon.

2018-01-16 00:47 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +              {props.location.title}
spacing is off here

2018-01-16 00:48 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +    <div className="position-relative">
Replace this with `<CardBorderDiv className="position-relative">` and remove the `<CardBorderDiv>` above

2018-01-16 00:49 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +              <div className = "pt-2">
Instead of nested divs with padding here, lets use margin + padding for the desired effect e.g. `pt-2 mt-4`

2018-01-16 00:50 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +          />
spacing is weird here

2018-01-16 00:50 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +    <LocationImage
Don't need that outer wrapper `<div>`, it does nothing

2018-01-16 00:53 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +function LocationSubTitleHelper(props) {
I would actually just axe this entire component here and replace the call with direct use of `LocationImage`, this seems like clutter and it's name is confusing

2018-01-16 00:53 UTC, Octember commented on app/components/LocationSubTitle/index.js
> +      <SubTitleOverlayDiv className="position-absolute px-2 w-100 h-100 ">
Love how this turned out!

2018-01-16 00:54 UTC, Octember requested changes
Overall looks solid, I'm stoked to get this merged in. A few requests around unecessary divs and stuff. 🔥

2018-01-17 01:53 UTC, ezraschwaa commented on app/components/LocationSubTitle/index.js
> +                  <img src="https://www.shareicon.net/data/128x128/2016/06/06/582476_location_16x16.png" width = "12" height = "15.6"/>
Rob sent me the images for the 1st and 3rd image, but I don't know how to upload to server

2018-01-17 02:02 UTC, Octember approved these changes
:shipit: :shipit:

2018-01-17 02:05 UTC, merged